import { useEffect, useState } from 'react';
import portrait from './assets/profile.png';
import './App.css';
const email = 'irfankkhan255@gmail.com';
const linkedin = 'https://www.linkedin.com/in/irfan-asghar-aa4a63354/';
const github = 'https://github.com/Irfan-Asghar-Baloch';
const navigation = ['Work', 'Expertise', 'About', 'Experience'];
const projects = [
 {id:'01',group:'Enterprise',name:'Enterprise MIS',kind:'PROFESSIONAL CONTRIBUTION',desc:'Connecting people, payroll and operations.',problem:'HR and business operations need consistent data across departments and reports.',work:'Backend APIs for attendance, loans, medical and payroll workflows, with transactional updates, attachments and Excel reporting.',stack:['ASP.NET Core','SQL Server','Dapper']},
 {id:'02',group:'Enterprise',name:'EMR & claims workflows',kind:'PROFESSIONAL CONTRIBUTION',desc:'Bringing structure to healthcare data.',problem:'Imported claim data must map correctly to patients, payers, physicians and charges.',work:'Excel import validation, duplicate checks, mapping logic, HL7 parsing and application maintenance.',stack:['C#','SQL Server','HL7','Excel']},
 {id:'03',group:'AI',name:'LLM support API',kind:'PRACTICE PROJECT',desc:'From a support request to structured action.',problem:'Free-text support requests need clear intent and reliable integration with order services.',work:'Gemini intent extraction, Pydantic responses, RAG retrieval and external API timeout/error handling.',stack:['Python','FastAPI','Gemini','Pydantic']},
 {id:'04',group:'Enterprise',name:'MaxChat',kind:'PROFESSIONAL CONTRIBUTION',desc:'Supporting real-time conversations.',problem:'Messaging workflows need live updates and connected backend services.',work:'Communication APIs, SignalR chat events, database queries and real-time integrations.',stack:['.NET','SignalR','WebRTC']},
];
const expertise = [
 ['01','Backend engineering','Reliable foundations for connected applications.',['C# / ASP.NET Core','REST APIs','Clean Architecture','Microservices','JWT / RBAC']],
 ['02','AI & automation','Connecting language models to useful workflows.',['Python / FastAPI','LLM integration','AI agents','RAG','Speech integration']],
 ['03','Full-stack development','Interfaces that make complex workflows usable.',['React','TypeScript','MUI','SignalR','WebRTC']],
 ['04','Data & integrations','Moving data accurately across system boundaries.',['SQL Server','Dapper / EF Core','Redis','RabbitMQ','Webhooks']],
];
function Arrow(){return <span aria-hidden="true">↗</span>}
function App(){
 const [menu,setMenu]=useState(false);const [filter,setFilter]=useState('All');const [active,setActive]=useState('');const [copied,setCopied]=useState(false);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActive(e.target.id)},{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!menu)return;const close=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menu]);
 async function copyEmail(){try{await navigator.clipboard.writeText(email);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setCopied(false)}}
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><a className="brand" href="#home" aria-label="Irfan Asghar home">ia<span>.</span><span className="brand-name">IRFAN ASGHAR</span></a><button className="menu-toggle" aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'} <span aria-hidden="true">{menu?'×':'☰'}</span></button><nav id="main-nav" className={menu?'navigation open':'navigation'} aria-label="Main navigation">{navigation.map(n=><a key={n} href={`#${n.toLowerCase()}`} aria-current={active===n.toLowerCase()?'location':undefined} onClick={()=>setMenu(false)}>{n}</a>)}</nav><a className="nav-contact" href="#contact">Let’s talk <Arrow/></a></div></header>
 <main id="main"><section id="home" className="hero container"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> FULL-STACK AI ENGINEER</p><h1>Engineering<br/>software.<br/><em>Connecting AI.</em></h1><p className="hero-description">I’m Irfan Asghar. I turn business workflows into connected applications with <strong>.NET, Python and React.</strong></p><div className="actions"><a className="button primary" href="#work">Explore my work <Arrow/></a><a className="button quiet" href={linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow/></a></div><div className="hero-location"><svg aria-hidden="true" width="14" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg> Islamabad / Rawalpindi, Pakistan</div></div><div className="hero-visual"><div className="portrait-card"><img src={portrait} alt="Irfan Asghar" fetchPriority="high"/><div className="portrait-overlay"><span>DEVELOPER · PROBLEM SOLVER</span><strong>Irfan Asghar</strong></div></div><div className="stack-label"><span className="status-dot"/> .NET <span>/</span> Python <span>/</span> React</div><div className="visual-caption"><span>01 — THE PERSON BEHIND THE CODE</span><span>↗</span></div></div></section>
 <div className="proof-strip container"><div><strong>2+ <span>years</span></strong><p>Professional .NET experience</p></div><div><strong>Healthcare</strong><p>Enterprise domain experience</p></div><div><strong>AI + software</strong><p>Applied engineering focus</p></div><div><strong>3.96<span>/4.0</span></strong><p>BSCS · Gold medalist</p></div></div>
 <section id="work" className="section container"><p className="eyebrow">01 / SELECTED WORK</p><div className="section-heading"><h2>Built around<br/><em>real workflows.</em></h2><p>Enterprise contributions and hands-on AI projects.<br/>A look at the problems I work on.</p></div><article className="featured-project"><div className="featured-copy"><div className="project-meta"><span>FEATURED / AI AGENT</span><span className="development">In development</span></div><h3>EHR Demo Agent</h3><p className="feature-intro">Bringing voice, meetings and healthcare software into one demo workflow.</p><p className="muted">At MaxRemind, I’m developing an AI-assisted meeting agent that greets participants, plays an introduction and connects the conversation to EHR screen sharing.</p><div className="feature-details"><div><span>MY CONTRIBUTION</span><p>Meeting integration, sequential audio playback, speech-provider fallbacks and runtime telemetry.</p></div><div><span>CURRENT DIRECTION</span><p>Automatic EHR login, dashboard navigation and explanation remain ongoing work.</p></div></div><div className="tags">{['.NET','LLMs','Recall','Speech services'].map(t=><span key={t}>{t}</span>)}</div></div><div className="workflow-visual" aria-label="EHR demo agent workflow illustration"><div className="workflow-top"><span className="status-dot"/> WORKFLOW / EHR DEMO<span className="visual-label">CONCEPT VIEW</span></div><div className="workflow-node"><span className="node-icon">01</span><div><strong>Meeting connection</strong><small>Participant detection</small></div><span className="node-state">INTEGRATION</span></div><div className="workflow-connector" aria-hidden="true"/><div className="workflow-node"><span className="node-icon">02</span><div><strong>Voice introduction</strong><small>Sequential speech playback</small></div><span className="waveform" aria-hidden="true">▂ ▆ ▃ █ ▄ ▇ ▂</span></div><div className="workflow-connector" aria-hidden="true"/><div className="workflow-node"><span className="node-icon">03</span><div><strong>EHR screen share</strong><small>Connected demo experience</small></div><span className="node-state">WORKFLOW</span></div><div className="workflow-next"><span>↳</span> Login & dashboard automation <span className="development">Ongoing</span></div></div></article>
 <div className="work-toolbar"><span>MORE SELECTED WORK</span><div className="filters" aria-label="Filter projects">{['All','AI','Enterprise'].map(f=><button key={f} onClick={()=>setFilter(f)} aria-pressed={filter===f}>{f}</button>)}</div></div><div className="projects-grid" aria-live="polite">{projects.filter(p=>filter==='All'||p.group===filter).map(p=><article className="project-card" key={p.id}><div className="project-meta"><span>{p.kind}</span><span>{p.id}</span></div><h3>{p.name}</h3><p className="project-subtitle">{p.desc}</p><div className="case-detail"><span>THE PROBLEM</span><p>{p.problem}</p></div><div className="case-detail"><span>MY WORK</span><p>{p.work}</p></div><div className="tags">{p.stack.map(t=><span key={t}>{t}</span>)}</div></article>)}</div><p className="work-note">Employer work is described at a high level. Internal source code and demos are not publicly linked.</p></section>
 <section id="expertise" className="section section-toned"><div className="container"><p className="eyebrow">02 / ENGINEERING TOOLKIT</p><div className="section-heading"><h2>From the API<br/>to the <em>AI workflow.</em></h2><p>A backend foundation.<br/>A connected, full-stack approach.</p></div><div className="expertise-grid">{expertise.map(([n,title,desc,tags])=><article className="expertise-card" key={n}><span className="card-index">{n}</span><h3>{title}</h3><p>{desc}</p><ul>{tags.map(t=><li key={t}>{t}</li>)}</ul></article>)}</div></div></section>
 <section id="about" className="section container about-grid"><div><p className="eyebrow">03 / ABOUT ME</p><h2>A strong foundation.<br/><em>A practical AI direction.</em></h2><a className="inline-link" href={github} target="_blank" rel="noreferrer">Find me on GitHub <Arrow/></a></div><div className="about-copy"><p className="lead">I build software that fits the way people actually work.</p><p>My foundation is in .NET backend development: enterprise APIs, SQL workflows, authentication and integrations. At MaxRemind, my work spans business operations, healthcare applications and real-time communication.</p><p>Now, I’m extending that experience with Python, React, LLMs and AI agents. I enjoy understanding a workflow, connecting the right systems and making the result useful to the person using it.</p><div className="direction-note"><span>WHERE I’M HEADING</span><p>Forward Deployed Engineering — combining hands-on development with real business problem solving.</p></div></div></section>
 <section id="experience" className="section container experience-section"><p className="eyebrow">04 / PROFESSIONAL EXPERIENCE</p><div className="section-heading"><h2>Building at <em>MaxRemind.</em></h2><p>Enterprise systems and applied AI.</p></div><div className="timeline"><article className="experience-item"><div className="experience-label"><span className="status-dot"/>CURRENT · ADDITIONAL ROLE</div><div><h3>AI Engineer</h3><p className="company">MaxRemind Inc.</p></div><div><p>Developing an AI-assisted EHR demo workflow connecting meeting integrations, voice playback and screen sharing.</p><div className="tags"><span>AI agents</span><span>Speech integration</span><span>Workflow automation</span></div></div></article><article className="experience-item"><div className="experience-label"><span className="status-dot"/>CURRENT · BACKEND ROLE</div><div><h3>.NET Backend Developer</h3><p className="company">MaxRemind Inc.</p></div><div><p>Backend contributions across MIS, CRM, Provider Portal, Union Health System and MaxChat, including APIs, database workflows, reporting and integrations.</p><div className="tags"><span>ASP.NET Core</span><span>SQL Server</span><span>Dapper</span></div></div></article></div></section>
 <section id="contact" className="contact-section"><div className="container contact-grid"><div><p className="eyebrow">05 / LET’S CONNECT</p><h2>Have a workflow<br/>worth <em>building?</em></h2><p>Let’s talk enterprise software, full-stack development and bringing AI into everyday operations.</p><a className="button primary" href={`mailto:${email}`}>Start a conversation <Arrow/></a></div><div className="contact-panel"><span className="contact-label">EMAIL</span><a className="email-link" href={`mailto:${email}`}>{email} <Arrow/></a><button className="copy-button" onClick={copyEmail}>{copied?'Copied ✓':'Copy email'}</button><span className="sr-only" role="status">{copied?'Email address copied':''}</span><div className="social-row"><a href={linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow/></a><a href={github} target="_blank" rel="noreferrer">GitHub <Arrow/></a></div><p className="contact-location">Based in Pakistan · Working across .NET, Python & React</p></div></div></section></main><footer className="container footer"><span>© {new Date().getFullYear()} Irfan Asghar</span><span>Built with React. Driven by real problems.</span><a href="#home">Back to top ↑</a></footer></>;
}
export default App;
